# ------------------------------
# 构建阶段
# ------------------------------
FROM golang:1.23 AS builder

WORKDIR /app
COPY . .

# 重点：设置 CGO_ENABLED=0，并显式指定 GOOS/GOARCH
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o bin/linux_amd64/main main.go


# ------------------------------
# 运行阶段
# ------------------------------
FROM alpine:3.8

# 设置环境变量为上海时区
ENV TZ=Asia/Shanghai
RUN apk add --no-cache tzdata && \
    cp /usr/share/zoneinfo/$TZ /etc/localtime && \
    echo $TZ > /etc/timezone
# 如果还有其他资源文件需要一起打包，比如配置文件等
# 可以继续 COPY 或 ADD 到指定位置
# 例如:
# COPY resource /app/resource

WORKDIR /app

# 将编译好的可执行文件复制到 /usr/bin/ 下面
COPY --from=builder /app/bin/linux_amd64/main /usr/bin/main

# 给可执行文件加上执行权限
RUN chmod +x /usr/bin/main

# 暴露端口（如果需要）
EXPOSE 8808

# 直接用命令名字做启动命令
CMD ["main"]
